name: Win32-CI
on: [push, pull_request]

env:
  QT_VERSION: "5.15.0"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw81
          version: ${{ env.QT_VERSION }}
      - name: Build tworld2
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DOSHW=qt `
            "-DCMAKE_PREFIX_PATH=${Env:RUNNER_WORKSPACE}/Qt/${Env:QT_VERSION}/mingw81_64" `
            "-DCMAKE_INSTALL_PREFIX=${Env:$GITHUB_WORKSPACE}/dist-qt" `
            "-DCMAKE_BUILD_TYPE=Debug" ..
          cmake --build .
          cmake --build . --target install
